<a href="https://colab.research.google.com/github/jawads12/BongoJourney.AI/blob/main/place1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/BongoJourney.AI/chittagong.csv')
df

,User-ID,Budget,Day,Place 1,Place 2,Place 3,Place 4,Place 5,Place 6,Gender,Children,with,season
0,202300101,23322,1,Patenga,Parkir Chor,Suptadhara,Satkania,NaN,NaN,Female,Yes,Alone,Summer
1,202300102,24549,4,Parkir Chor,Satkania,Chandranath,Bashkhali,KhaiyaChora,NaN,Other,Yes,Couple,Summer
2,202300103,17541,1,Suptadhara,NaN,NaN,NaN,NaN,NaN,Female,No,Friends,Autumn
3,202300104,23667,1,Raojan,NaN,NaN,NaN,NaN,NaN,Male,Yes,Alone,Autumn
4,202300105,23833,3,Chittagong University,Parkir Chor,Bashkhali,Fatikchari,Chandranath,NaN,Male,No,Couple,Autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,202301096,21663,7,Suptadhara,Raojan,Satkania,Chandranath,NaN,NaN,Other,Yes,Friends,Summer
996,202301097,12651,6,Chandranath,Guliakhali,NaN,NaN,NaN,NaN,Other,Yes,Friends,Rainy
997,202301098,15555,1,Chandranath,Suptadhara,Guliakhali,Parkir Chor,Bashkhali,Chittagong University,Female,No,Family,Winter
998,202301099,29293,2,Patenga,Fatikchari,NaN,NaN,NaN,NaN,Other,Yes,Family,Rainy
999,202301100,13609,3,Fatikchari,Parkir Chor,Chandranath,NaN,NaN,NaN,Female,No,Alone,Winter

In [ ]:
df.info

<bound method DataFrame.info of        User-ID  Budget  Day                Place 1      Place 2      Place 3  \
0    202300101   23322    1                Patenga  Parkir Chor   Suptadhara
1    202300102   24549    4            Parkir Chor     Satkania  Chandranath
2    202300103   17541    1             Suptadhara          NaN          NaN
3    202300104   23667    1                 Raojan          NaN          NaN
4    202300105   23833    3  Chittagong University  Parkir Chor    Bashkhali
..         ...     ...  ...                    ...          ...          ...
995  202301096   21663    7             Suptadhara       Raojan     Satkania
996  202301097   12651    6            Chandranath   Guliakhali          NaN
997  202301098   15555    1            Chandranath   Suptadhara   Guliakhali
998  202301099   29293    2                Patenga   Fatikchari          NaN
999  202301100   13609    3             Fatikchari  Parkir Chor  Chandranath

         Place 4      Place 5                Place 6  Gender Children  \
0       Satkania          NaN                    NaN  Female      Yes
1      Bashkhali  KhaiyaChora                    NaN   Other      Yes
2            NaN          NaN                    NaN  Female       No
3            NaN          NaN                    NaN    Male      Yes
4     Fatikchari  Chandranath                    NaN    Male       No
..           ...          ...                    ...     ...      ...
995  Chandranath          NaN                    NaN   Other      Yes
996          NaN          NaN                    NaN   Other      Yes
997  Parkir Chor    Bashkhali  Chittagong University  Female       No
998          NaN          NaN                    NaN   Other      Yes
999          NaN          NaN                    NaN  Female       No

        with  season
0      Alone  Summer
1     Couple  Summer
2    Friends  Autumn
3      Alone  Autumn
4     Couple  Autumn
..       ...     ...
995  Friends  Summer
996  Friends   Rainy
997   Family  Winter
998   Family   Rainy
999    Alone  Winter

[1000 rows x 13 columns]>

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'df' is your DataFrame
# Replace 'df' with the name of your DataFrame variable

# Initializing Label Encoders for each field
le_gender = LabelEncoder()
le_children = LabelEncoder()
le_with = LabelEncoder()
le_season = LabelEncoder()
le_place1 = LabelEncoder()
le_place2 = LabelEncoder()
le_place3 = LabelEncoder()
le_place4 = LabelEncoder()
le_place5 = LabelEncoder()
le_place6 = LabelEncoder()

# Fill None values with a placeholder for encoding
df.fillna('None', inplace=True)

# Applying Label Encoding to the fields
df['Gender'] = le_gender.fit_transform(df['Gender'])
df['Children'] = le_children.fit_transform(df['Children'])
df['with'] = le_with.fit_transform(df['with'])
df['season'] = le_season.fit_transform(df['season'])
df['Place 1'] = le_place1.fit_transform(df['Place 1'])
df['Place 2'] = le_place2.fit_transform(df['Place 2'])
df['Place 3'] = le_place3.fit_transform(df['Place 3'])
df['Place 4'] = le_place4.fit_transform(df['Place 4'])
df['Place 5'] = le_place5.fit_transform(df['Place 5'])
df['Place 6'] = le_place6.fit_transform(df['Place 6'])

# Display the first few rows of the DataFrame after label encoding
print(df.head())

     User-ID  Budget  Day  Place 1  Place 2  Place 3  Place 4  Place 5  \
0  202300101   23322    1        7        7       11       10        6
1  202300102   24549    4        6       10        1        0        5
2  202300103   17541    1       10        6        6        6        6
3  202300104   23667    1        8        6        6        6        6
4  202300105   23833    3        2        7        0        3        1

   Place 6  Gender  Children  with  season
0        6       0         1     0       2
1        6       2         1     1       2
2        6       0         0     3       0
3        6       1         1     0       0
4        6       1         0     1       0

In [ ]:
# Assuming no_null_df is your DataFrame

# Dropping all place fields except 'Place 1'
DF1 = df.drop(['Place 2', 'Place 3', 'Place 4', 'Place 5', 'Place 6'], axis=1)
DF2 = df.drop(['Place 1', 'Place 3', 'Place 4', 'Place 5', 'Place 6'], axis=1)
DF3 = df.drop(['Place 2', 'Place 1', 'Place 4', 'Place 5', 'Place 6'], axis=1)
DF4 = df.drop(['Place 2', 'Place 3', 'Place 1', 'Place 5', 'Place 6'], axis=1)
DF5 = df.drop(['Place 2', 'Place 3', 'Place 4', 'Place 1', 'Place 6'], axis=1)
DF6 = df.drop(['Place 2', 'Place 3', 'Place 4', 'Place 5', 'Place 1'], axis=1)


# Now df_reduced will have all columns except the ones dropped
DF1

       User-ID  Budget  Day  Place 1  Gender  Children  with  season
0    202300101   23322    1        7       0         1     0       2
1    202300102   24549    4        6       2         1     1       2
2    202300103   17541    1       10       0         0     3       0
3    202300104   23667    1        8       1         1     0       0
4    202300105   23833    3        2       1         0     1       0
..         ...     ...  ...      ...     ...       ...   ...     ...
995  202301096   21663    7       10       2         1     3       2
996  202301097   12651    6        1       2         1     3       1
997  202301098   15555    1        1       0         0     2       3
998  202301099   29293    2        7       2         1     2       1
999  202301100   13609    3        3       0         0     0       3

[1000 rows x 8 columns]

In [ ]:
# Assuming le_gender is the LabelEncoder instance for the Gender column

# Finding the encoded number for "Male"
male_encoded = dict(zip(le_place1.classes_, le_place1.transform(le_place1.classes_)))["Chittagong University"]

print(f"The number assigned to 'Male' is: {male_encoded}")

The number assigned to 'Male' is: 2

In [ ]:
# Assuming le_gender is the LabelEncoder instance for the Gender column

# Finding the original value for the encoded number 2
original_value = le_place1.inverse_transform([2])[0]

print(f"The original value for the encoded number  is: {original_value}")

The original value for the encoded number  is: Chittagong University

Test data and Train Data Separation

In [ ]:
df

,User-ID,Budget,Day,Place 1,Place 2,Place 3,Place 4,Place 5,Place 6,Gender,Children,with,season
0,202300101,23322,1,7,7,11,10,6,6,0,1,0,2
1,202300102,24549,4,6,10,1,0,5,6,2,1,1,2
2,202300103,17541,1,10,6,6,6,6,6,0,0,3,0
3,202300104,23667,1,8,6,6,6,6,6,1,1,0,0
4,202300105,23833,3,2,7,0,3,1,6,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,202301096,21663,7,10,9,10,1,6,6,2,1,3,2
996,202301097,12651,6,1,4,6,6,6,6,2,1,3,1
997,202301098,15555,1,1,11,4,7,0,2,0,0,2,3
998,202301099,29293,2,7,3,6,6,6,6,2,1,2,1
999,202301100,13609,3,3,7,1,6,6,6,0,0,0,3

In [ ]:
DF1

       User-ID  Budget  Day  Place 1  Gender  Children  with  season
0    202300101   23322    1        7       0         1     0       2
1    202300102   24549    4        6       2         1     1       2
2    202300103   17541    1       10       0         0     3       0
3    202300104   23667    1        8       1         1     0       0
4    202300105   23833    3        2       1         0     1       0
..         ...     ...  ...      ...     ...       ...   ...     ...
995  202301096   21663    7       10       2         1     3       2
996  202301097   12651    6        1       2         1     3       1
997  202301098   15555    1        1       0         0     2       3
998  202301099   29293    2        7       2         1     2       1
999  202301100   13609    3        3       0         0     0       3

[1000 rows x 8 columns]

In [ ]:
from sklearn.model_selection import train_test_split


# Preparing the features (X) and target (y)
X = DF1.drop('Place 1', axis=1)  # All columns except 'Place 1'
y = DF1['Place 1']  # 'Place 1' column as the target

# Splitting the dataset into training and test sets
# Setting test_size=0.2 means 20% of the data will be used for testing, and 80% for training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# X_train, y_train are the training features and target
# X_test, y_test are the testing features and target

Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest Classifier instance
rf_classifier = RandomForestClassifier(random_state=42)

# Train the classifier with the training data
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

make predictions

In [ ]:
# Making predictions on the test data
y_pred = rf_classifier.predict(X_test)

accuracy

In [ ]:
from sklearn.metrics import accuracy_score

# Calculating the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the model: {accuracy}")

Accuracy of the model: 0.08

In [ ]:
y_pred

array([ 1,  1,  0,  2,  2, 10,  4,  3,  8, 10,  8,  2,  1,  0,  1,  7,  5,
        0,  4,  5,  1,  4,  1,  6,  1,  0,  8,  1,  2,  5,  9,  3,  5,  9,
       10,  3,  1,  3,  7,  6,  2,  8,  7,  4,  1,  8, 10,  2,  3, 10,  4,
        7,  5,  4,  6,  2, 10,  4,  7,  6,  4,  5,  1,  6,  0,  5,  7,  9,
        6,  3,  9,  1,  9,  3,  7,  2,  0,  6,  5,  6,  1,  8, 10,  5,  4,
        1,  1,  1,  1,  7,  1,  9,  2,  5,  7,  5,  1,  9,  7,  6,  6,  3,
        8,  0,  7,  5,  5,  1,  8,  7,  1,  3,  1,  5,  8,  8,  1,  1,  7,
        1,  3,  1,  7,  6,  5,  4,  8,  8,  4,  2, 10,  0,  8,  7,  8,  6,
       10,  4,  5,  9,  1,  1,  3,  0,  1,  7,  9,  5,  9,  1,  1, 10,  3,
        0,  1,  5,  3,  0,  1,  7, 10,  6,  7, 10,  7, 10,  2,  3, 10,  1,
        5,  3,  5,  4,  9,  7,  1,  3,  7,  9,  4,  1, 10,  1,  2, 10,  4,
        4,  2,  7,  1, 10,  1,  5,  6,  7, 10,  9,  3,  6])

In [ ]:
DF1

       User-ID  Budget  Day  Place 1  Gender  Children  with  season
0    202300101   23322    1        7       0         1     0       2
1    202300102   24549    4        6       2         1     1       2
2    202300103   17541    1       10       0         0     3       0
3    202300104   23667    1        8       1         1     0       0
4    202300105   23833    3        2       1         0     1       0
..         ...     ...  ...      ...     ...       ...   ...     ...
995  202301096   21663    7       10       2         1     3       2
996  202301097   12651    6        1       2         1     3       1
997  202301098   15555    1        1       0         0     2       3
998  202301099   29293    2        7       2         1     2       1
999  202301100   13609    3        3       0         0     0       3

[1000 rows x 8 columns]

In [ ]:
input_features = {
    'Budget': '1000',  # Example feature
    'Gender' : 'Male'
    # ... other features
}
encoded_features = [feature_encoder.transform([input_features[feature]])[0] for feature in input_features]

# Step 2: Predict with the Random Forest model
predicted_place_num = rf_classifier.predict([encoded_features])[0]

# Step 3: Convert the predicted numeric value back to text
predicted_place_name = place_encoder.inverse_transform([predicted_place_num])[0]